export const jewelryLinkCreateOwn = () => cy.get('[data-productid="71"] .product-title [href]')
export const materialDropdown = () => cy.get('[name="product_attribute_71_9_15"]')
export const lengthInCmInput  = () => cy.get('[name="product_attribute_71_10_16"]')
export const pendantLadybugRadioButton  = () => cy.get('[name="product_attribute_71_11_17"][value="48"]')
export const quantityInput  = () => cy.get('[name="addtocart_71.EnteredQuantity"]')
export const addToWishlistButton  = () => cy.get('#add-to-wishlist-button-71')