version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  smoke:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: 'npm run e2e:ci:cypress:dashboard:smoke'