name: Cypress Workflow

on: pull_request

jobs:
  cypress-run:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Regression tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          group: '2 - regression tests'
          tag: regression
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}