name: Cypress Smoke Tests

on: workflow_dispatch

jobs:
  cypress-run-smoke:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run smoke tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e:run:cypress:dashboard:smoke
          browser: chrome
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}